enum authConstants {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_FAILURE_RESET,
  LOGIN_NEW_PASSWORD,
  LOGIN_PASSWORD_RESET,
  PASSWORD_RESET_REQUEST,
  PASSWORD_RESET_FAILURE,
  PASSWORD_RESET_FAILURE_RESET,
  BACK_TO_LOGIN,
  SIGNUP_REQUEST,
  SIGNUP_REQUEST_COMPLETE,
  SIGNUP_FAILURE,
  SIGNUP_SUCCESS,
  RESEND_SIGNUP_REQUEST,
  RESEND_SIGNUP_SUCCESS,
  RESEND_SIGNUP_FAILURE,
  SIGNUP_VERIFICATION_REQUEST,
  SIGNUP_VERIFICATION_FAILURE,
  SIGNUP_FAILURE_RESET,
  RESEND_SIGNUP_FAILURE_RESET,
  RESEND_SIGNUP_SUCCESS_RESET,
  SIGNUP_VERIFICATION_FAILURE_RESET,
  RESET_SIGNED_UP
}

export { authConstants };