enum authConstants {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_FAILURE_RESET,
  LOGIN_NEW_PASSWORD,
  LOGIN_PASSWORD_RESET,
  PASSWORD_RESET_REQUEST,
  PASSWORD_RESET_SUCCESS
}

export { authConstants };